# Generated by Django 3.1.1 on 2020-12-19 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='creator',
        ),
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='goals_against',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='goals_for',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='blog.league'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
